#ifndef __DEFINITIONS_INCLUDED__   
#define __DEFINITIONS_INCLUDED__

#define EXTENDED_SWITCH_PIN -1
#define RETRACTED_SWITCH_PIN -1
#define WINCH_MOTOR_PIN -1
#define FORWARD_TIME_LIMIT -1
#define REVERSE_TIME_LIMIT -1
#define WINCH_MOTOR_FORWARD -1
#define WINCH_MOTOR_REVERSE -1
#define WINCH_MOTOR_NEUTRAL -1
#define SONAR1_PIN -1
#define SONAR2_PIN -1
#define SONAR3_PIN -1
#define SONAR4_PIN -1
#define SONAR5_PIN -1
#define SONAR6_PIN -1
#define SONAR7_PIN -1
#define SONAR8_PIN -1

#define SONAR9_PIN -1
#define SONAR10_PIN -1
#define SONAR11_PIN -1
#define SONAR12_PIN -1
#define SONAR13_PIN -1
#define SONAR14_PIN -1
#define SONAR15_PIN -1
#define SONAR16_PIN -1

#define PROBE_MOVING_FORWARD 1
#define PROBE_MOVING_REVERSE 2
#define PROBE_EXTENDED 3
#define PROBE_RETRACTED 4

#define RECHARGE_START 1
#define RECHARGE_STOP 2
#define RECHARGE_WAIT 3

#define NO_ERROR 0
#define EXTENSION_ERROR 1
#define RETRACTION_ERROR 2

#define TARGET_NONE 1
#define TARGET_TRACKING 2

#endif
